import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

      >
        <Navbar />
        <div className="flex flex-row w-100">
            <div className="w-20 h-screen bg-amber-400"><Sidebar /></div>
        <div className="w-80 bg-amber-900">
            {children}
            </div> 
        </div>
      </body>
    </html>
  );
}
